Update hostKCD.md : Replace Checkboxes with Bullet Points and Fix Typo in Financial Officer
cncf/kubernetes-community-days pull request #483
Opened 2023-05-01 11:41 UTC by chamodshehanka

* Remove checkboxes in details section and replaced with bullet points 
* Fixed a typo in `financial officer`

2023-05-03 13:54 UTC, AudMonte01 requested changes
We will leave the event details as check boxes for when people fill out those details. Some take some time to figure out venue or dates.

2023-05-03 14:15 UTC, chamodshehanka commented
> We will leave the event details as check boxes for when people fill out those details. Some take some time to figure out venue or dates.

Ohh! Got it!

2023-05-03 15:48 UTC, AudMonte01 approved these changes

2023-06-05 18:55 UTC, caniszczyk commented
@chamodshehanka can you reopen this PR with a new PR? we removed Netlify checks which aren't used anymore

2023-06-05 18:55 UTC, closed without merging